# Generated by Django 5.2.8 on 2025-11-11 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={'verbose_name': 'Doação', 'verbose_name_plural': 'Doações'},
        ),
    ]
