# Generated by Django 5.2.8 on 2025-11-11 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduleentry',
            options={'ordering': ['day', 'shift', 'activity'], 'verbose_name': 'Atividade do Cronograma', 'verbose_name_plural': 'Atividades do Cronograma'},
        ),
    ]
