# Generated by Django 5.1.3 on 2025-11-16 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_contact_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="phone",
            field=models.CharField(
                blank=True, default="", max_length=30, verbose_name="Telefone"
            ),
        ),
    ]
