# Generated by Django 5.2.8 on 2025-11-11 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participation',
            options={'verbose_name': 'Participação', 'verbose_name_plural': 'Participações'},
        ),
    ]
